version: 2.1

orbs:
  docker: circleci/docker@3.0.1

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: kilinco/udagram-api-feed
          path: ./udagram-api-feed
          tag: <<pipeline.git.revision>>
      - docker/publish:
          image: kilinco/udagram-api-user
          path: ./udagram-api-user
          tag: <<pipeline.git.revision>>
      - docker/publish:
          image: kilinco/udagram-frontend
          path: ./udagram-frontend
          tag: <<pipeline.git.revision>>
      - docker/publish:
          image: kilinco/reverseproxy
          path: ./udagram-reverseproxy
          tag: <<pipeline.git.revision>>